on: 
  push:
      branches:
          - main
name: Production Deploy
jobs:
  FTP-Deploy-Action:
    name:  FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ftpupload.net
        ftp-username: 	b9_35274743
        ftp-password: Atul@2012

    
